"""update columns

Revision ID: 38851b1adaa3
Revises: 28686a7cc681
Create Date: 2024-07-14 20:19:25.465312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38851b1adaa3'
down_revision = '28686a7cc681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('suppliers')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_products_supplier_id_suppliers', type_='foreignkey')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))
        batch_op.drop_constraint('fk_transactions_product_id_products', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_transactions_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('companyName', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('country', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.TEXT(), nullable=True))
        batch_op.drop_column('city')
        batch_op.drop_column('country')
        batch_op.drop_column('companyName')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_transactions_product_id_products', 'products', ['product_id'], ['id'])
        batch_op.drop_column('type')
        batch_op.drop_column('total_price')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_products_supplier_id_suppliers', 'suppliers', ['supplier_id'], ['id'])
        batch_op.drop_column('quantity')
        batch_op.drop_column('sku')

    op.create_table('suppliers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('date_received', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_orders_product_id_products'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
