"""Remove orders table

Revision ID: dbd1aa0778e4
Revises: 38a0d3d564e4
Create Date: 2024-07-14 21:53:06.955658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd1aa0778e4'
down_revision = '38a0d3d564e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('suppliers')
    # op.drop_table('orders')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.String(), nullable=True))
        batch_op.drop_constraint('fk_products_supplier_id_suppliers', type_='foreignkey')
        batch_op.drop_column('supplier_id')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('supplier_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_products_supplier_id_suppliers', 'suppliers', ['supplier_id'], ['id'])
        batch_op.drop_column('quantity')
        batch_op.drop_column('sku')

    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('date_received', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_orders_product_id_products'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
